version: "3"
services:
  db:
    image: "mysql:5.7"
    volumes:
#      - "./data:/var/lib/mysql"
      - "./wordpress.sql:/docker-entrypoint-initdb.d/wordpress.sql"
    restart: $RESTART
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
  pma:
    image: "phpmyadmin/phpmyadmin:4.7.8-1"
    depends_on:
      - db
    ports:
      - "9000:80"
    environment:
      PMA_HOST: db
      PMA_PORT: $MYSQL_PORT
      PMA_USER: $MYSQL_USERNAME
      PMA_PASSWORD: $MYSQL_PASSWORD
  wordpress:
    image: "nothingspare/wordpress-memcached-exif:4.9.8"
    depends_on:
      - db
    privileged: true
    ports:
      - "$WP_PORT:80"
    volumes:
      - "./plugin:/var/www/html/wp-content/plugins/$PLUGIN_NAME"
      - "wordpress_content:/var/www/html/wp-content/plugins"
      - "./wp-config.php:/var/www/html/wp-config.php"
    restart: $RESTART
volumes:
  wordpress_content:
